import React, { Component } from "react";
import "./Select.css";

export default class Select extends Component {
  render() {
    return (
      <div>
        <select class="input-text">
          <option value="0" selected="selected">
            Quốc gia
          </option>
          <option value="1">Afghanistan</option>
          <option value="2">Ả Rập Ai Cập</option>
          <option value="3">Albania</option>
          <option value="4">Algérie</option>
          <option value="5">Andorra</option>
          <option value="6">Angola</option>
          <option value="7">Anh và Bắc Ireland</option>
          <option value="8">Antigua và Barbuda</option>
          <option value="9">Áo</option>
          <option value="10">Ả Rập Xê Út</option>
          <option value="11">Argentina</option>
          <option value="12">Armenia</option>
          <option value="13">Azerbaijan</option>
          <option value="14">Ấn Độ</option>
          <option value="15">Bahamas</option>
          <option value="16">Bahrain</option>
          <option value="17">Ba Lan</option>
          <option value="18">Bangladesh</option>
          <option value="19">Barbados</option>
          <option value="20">Bắc Macedonia</option>
          <option value="21">Belarus</option>
          <option value="22">Belize</option>
          <option value="23">Benin</option>
          <option value="24">Bhutan</option>
          <option value="25">Bỉ</option>
          <option value="26">Bolivia</option>
          <option value="27">Bosna và Hercegovina</option>
          <option value="28">Botswana</option>
          <option value="29">Bồ Đào Nha</option>
          <option value="30">Bờ Biển Ngà</option>
          <option value="31">Brazil</option>
          <option value="32">Brunei</option>
          <option value="33">Bulgaria</option>
          <option value="34">Burkina Faso</option>
          <option value="35">Burundi</option>
          <option value="36">Cabo Verde</option>
          <option value="37">Cameroon</option>
          <option value="38">Campuchia</option>
          <option value="39">Canada</option>
          <option value="40">Chile</option>
          <option value="41">Colombia</option>
          <option value="42">Comoros</option>
          <option value="43">Công-gô</option>
          <option value="44">Costa Rica</option>
          <option value="45">Croatia</option>
          <option value="46">Cuba</option>
          <option value="47">Djibouti</option>
          <option value="48">Dominica</option>
          <option value="49">Đan Mạch</option>
          <option value="50">Đông Timor</option>
          <option value="51">Đức</option>
          <option value="52">Ecuador</option>
          <option value="53">El Salvador</option>
          <option value="54">Eritrea</option>
          <option value="55">Estonia</option>
          <option value="56">Eswatini</option>
          <option value="57">Ethiopia</option>
          <option value="58">Fiji</option>
          <option value="59">Gabon</option>
          <option value="60">Gambia</option>
          <option value="61">Ghana</option>
          <option value="62">Grenada</option>
          <option value="63">Gruzia</option>
          <option value="64">Guatemala</option>
          <option value="65">Guiné-Bissau</option>
          <option value="66">Guinea Xích Đạo</option>
          <option value="67">Guinée</option>
          <option value="68">Guyana</option>
          <option value="69">Haiti</option>
          <option value="70">Hà Lan</option>
          <option value="71">Hàn Quốc</option>
          <option value="72">Hoa Kỳ</option>
          <option value="73">Honduras</option>
          <option value="74">Hungary</option>
          <option value="75">Hy Lạp</option>
          <option value="76">Iceland</option>
          <option value="77">Indonesia</option>
          <option value="78">Iran</option>
          <option value="79">Iraq</option>
          <option value="80">Ireland</option>
          <option value="81">Israel</option>
          <option value="82">Jamaica</option>
          <option value="83">Jordan</option>
          <option value="84">Kazakhstan</option>
          <option value="85">Kenya</option>
          <option value="86">Kiribati</option>
          <option value="87">Kosovo</option>
          <option value="88">Kuwait</option>
          <option value="89">Kyrgyzstan</option>
          <option value="90">Lào</option>
          <option value="91">Latvia</option>
          <option value="92">Lesotho</option>
          <option value="93">Liban</option>
          <option value="94">Liberia</option>
          <option value="95">Libya</option>
          <option value="96">Liechtenstein</option>
          <option value="97">Luxembourg</option>
          <option value="98">Madagascar</option>
          <option value="99">Malaysia</option>
          <option value="100">Maldives</option>
          <option value="101">Mali</option>
          <option value="102">Malta</option>
          <option value="103">Maroc</option>
          <option value="104">Marshall</option>
          <option value="105">Mauritanie</option>
          <option value="106">Mauritius</option>
          <option value="107">Mexico</option>
          <option value="108">Micronesia</option>
          <option value="109">Moldova</option>
          <option value="110">Monaco</option>
          <option value="111">Mông Cổ</option>
          <option value="112">Montenegro</option>
          <option value="113">Mozambique</option>
          <option value="114">Myanmar</option>
          <option value="115">Namibia</option>
          <option value="116">Nam Sudan</option>
          <option value="117">Nam Phi</option>
          <option value="118">Nauru</option>
          <option value="119">Na Uy</option>
          <option value="120">Nepal</option>
          <option value="121">New Zealand</option>
          <option value="122">Nicaragua</option>
          <option value="123">Niger</option>
          <option value="124">Nigeria</option>
          <option value="125">Nga</option>
          <option value="126">Nhật Bản</option>
          <option value="127">Oman</option>
          <option value="128">Pakistan</option>
          <option value="129">Palau</option>
          <option value="130">Palestine</option>
          <option value="131">Panama</option>
          <option value="132">Papua New Guinea</option>
          <option value="133">Paraguay</option>
          <option value="134">Peru</option>
          <option value="135">Pháp</option>
          <option value="136">Phần Lan</option>
          <option value="137">Philippines</option>
          <option value="138">Qatar</option>
          <option value="139">Romania</option>
          <option value="140">Rwanda</option>
          <option value="141">Saint Kitts và Nevis</option>
          <option value="142">Saint Lucia</option>
          <option value="143">Saint Vincent và Grenadines</option>
          <option value="144">Samoa</option>
          <option value="145">San Marino</option>
          <option value="146">São Tomé và Príncipe</option>
          <option value="147">Séc</option>
          <option value="148">Sénégal</option>
          <option value="149">Serbia</option>
          <option value="150">Seychelles</option>
          <option value="151">Sierra Leone</option>
          <option value="152">Singapore</option>
          <option value="153">Síp</option>
          <option value="154">Slovakia</option>
          <option value="155">Slovenia</option>
          <option value="156">Solomon</option>
          <option value="157">Somalia</option>
          <option value="158">Sri Lanka</option>
          <option value="159">Sudan</option>
          <option value="160">Suriname</option>
          <option value="161">Syria</option>
          <option value="162">Tajikistan</option>
          <option value="163">Tanzania</option>
          <option value="164">Tây Ban Nha</option>
          <option value="165">Tchad</option>
          <option value="166">Thái Lan</option>
          <option value="167">Thổ Nhĩ Kỳ</option>
          <option value="168">Thụy Điển</option>
          <option value="169">Thụy Sĩ</option>
          <option value="170">Togo</option>
          <option value="171">Tonga</option>
          <option value="172">Triều Tiên</option>
          <option value="173">Trinidad và Tobago</option>
          <option value="174">Trung Quốc</option>
          <option value="175">Trung Phi</option>
          <option value="176">Tunisia</option>
          <option value="177">Turkmenisan</option>
          <option value="178">Tuvalu</option>
          <option value="179">Úc</option>
          <option value="180">Uganda</option>
          <option value="181">Ukraina</option>
          <option value="182">Uruguay</option>
          <option value="183">Uzbekistan</option>
          <option value="184">Vanuatu</option>
          <option value="185">Vatican</option>
          <option value="186">Venezuela</option>
          <option value="187">Việt Nam</option>
          <option value="188">Ý</option>
          <option value="189">Yemen</option>
          <option value="190">Zambia</option>
          <option value="191">Zimbabwe</option>
        </select>
      </div>
    );
  }
}
